### ISSUE TITLE
インストール時に404エラーが出る

### ISSUE THREAD

**Issue by Robot-Inventor** [textlint-ja/textlint-rule-preset-foreign-language-writing#13]
# 概要

[@textlint-ja/textlint-rule-kana-english-fo-pho](https://github.com/textlint-ja/textlint-rule-preset-foreign-language-writing/tree/master/packages/textlint-rule-kana-english-fo-pho)をインストールするために、書かれているとおりに

```
npm install @textlint-ja/textlint-rule-kana-english-fo-pho
```

を実行しても404エラーが出てインストールできません。また、@textlint-ja/textlint-rule-kana-english-fo-phoだけでなく[README.md](https://github.com/textlint-ja/textlint-rule-preset-foreign-language-writing/blob/master/README.md)のルール一覧に書かれているすべてのルールが404エラーでインストールできません。npmにパッケージとして登録されていないようです。

# エラー内容

npm install時に以下のメッセージが表示されます。

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@textlint-ja%2ftextlint-rule-kana-english-fo-pho - Not found
npm ERR! 404
npm ERR! 404  '@textlint-ja/textlint-rule-kana-english-fo-pho@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user_name\AppData\Roaming\npm-cache\_logs\2021-01-27T14_20_39_811Z-debug.log
```

また、C:\Users\user_name\AppData\Roaming\npm-cache\_logs\2021-01-27T14_20_39_811Z-debug.logの内容は次の通りです。

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@textlint-ja/textlint-rule-kana-english-fo-pho'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose npm-session ace7880be970d7d5
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@textlint-ja%2ftextlint-rule-kana-english-fo-pho 161ms
8 http fetch GET 404 https://registry.npmjs.org/@textlint-ja%2ftextlint-rule-kana-english-fo-pho 47ms
9 silly fetchPackageMetaData error for @textlint-ja/textlint-rule-kana-english-fo-pho@latest 404 Not Found - GET https://registry.npmjs.org/@textlint-ja%2ftextlint-rule-kana-english-fo-pho - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 270ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@textlint-ja%2ftextlint-rule-kana-english-fo-pho - Not found
12 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:117:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
13 verbose statusCode 404
14 verbose pkgid @textlint-ja/textlint-rule-kana-english-fo-pho@latest
15 verbose cwd C:\Users\user_name\desktop\test
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@textlint-ja/textlint-rule-kana-english-fo-pho"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/@textlint-ja%2ftextlint-rule-kana-english-fo-pho - Not found
22 error 404
23 error 404 '@textlint-ja/textlint-rule-kana-english-fo-pho@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]
```

# 環境

- Windows 10
- Node.js v14.15.4
- npm 6.14.11

**Comment by azu** [comment]
未完成な状態で止まっているのでpublishできていないためですね。
https://twitter.com/azu_re/status/1305885091176931328

**Comment by Robot-Inventor** [comment]
そういう事だったのですね。早い返信ありがとうございます！
